name: kiss_drift_repository
description: "A Drift implementation of kiss_repository interface"
version: 0.1.0
homepage: https://github.com/WAMF/kiss_drift_repository

environment:
  sdk: ^3.8.0

dependencies:
  drift: ^2.27.0
  sqlite3: ^2.4.0
  path: ^1.8.0
  uuid: ^4.5.1
  kiss_repository:
    path: ../kiss_repository

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^6.0.0
  drift_dev: ^2.27.0
  build_runner: ^2.4.0
  kiss_repository_tests:
    path: ../kiss_repository_tests
